import '@repo/main/styles.css';
import type { Metadata } from "next";
import NavBar from "./components/layout/navbar";
import "./globals.css"
import Footer from './components/layout/footer';

export const metadata: Metadata = {
  title: "سامانه آموزش",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="bg-background text-foreground">
        <div className='max-w-7xl mx-auto px-4 sm:px-6 lg:px-8'>
          <NavBar />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
