import '@repo/main/styles.css';
import type { Metadata } from "next";
import Footer from './components/layout/footer';
import NavBar from "./components/layout/navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "سامانه آموزش",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="bg-background text-foreground">
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
